config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_scope :usuario do
    get "sign_out" => "devise/sessions#destroy"
    get "salir" => "devise/sessions#destroy",
      as: :terminar_sesion

    post "usuarios/iniciar_sesion",
      to: "devise/sessions#create"
    get "usuarios/iniciar_sesion",
      to: "devise/sessions#new",
      as: :iniciar_sesion

    # El siguiente para superar mala generación del action en el formulario
    # cuando se monta en sitio diferente a / y se autentica mal (genera
    # /puntomontaje/puntomontaje/usuarios/sign_in )
    if Rails.configuration.relative_url_root != "/"
      ruta = File.join(
        Rails.configuration.relative_url_root,
        "usuarios/sign_in",
      )
      post ruta, to: "devise/sessions#create"
      get  ruta, to: "devise/sessions#new"
    end
  end

  devise_for :usuarios, skip: [:registrations], module: :devise
  as :usuario do
    get "usuarios/edit" => "devise/registrations#edit",
      :as => "editar_registro_usuario"
    put "usuarios/:id" => "devise/registrations#update",
      :as => "registro_usuario"
  end

  resources :acto, only: [], param: :index do
    member do
      delete '(:id)', to: "sivel2_gen/actos#destroy", as: "eliminar"
      post '/', to: "sivel2_gen/actos#create", as: "crear"
    end
  end

  resources :aporte, only: [], param: :index do
    member do
      delete '(:id)', to: "aportes#destroy", as: "eliminar"
      post '/', to: "aportes#create", as: "crear"
    end
  end

  get "aportes/actualizacion_masiva",
    to:"msip/personas#actualizacion_masiva",
    as: :aportes_actualizacion_masiva
  patch "aportes/actualizacion_masiva",
    to: "msip/personas#hacer_actualizacion_masiva",
    as: :aportes_hacer_actualizacion_masiva

  resources :homonimos, path_names: { new: "nuevo", edit: "edita" },
    controller: "msip/homonimos"

  resources :usuarios, path_names: { new: "nuevo", edit: "edita" }



  get "/aliadoasiste/nuevo" => "cor1440_gen/actividades#nuevo_aliadoasiste",
    as: :nuevo_aliadoasiste

  #get "/consaportante/:id" => "msip/personas#show",
  #  as: :consaportante
  get "/consaportantes" => "consaportantes#index",
    as: :consaportantes

  get "/casos/mapaosm" => "sivel2_gen/casos#mapaosm"

  get "/casos/numcasos" => "sivel2_gen/casos#numcasos"

  get "/fasol/banco" => "sivel2_gen/conteos#fasol_banco",
    as: :banco

  get "/fasol/banco_regionales" =>
  "sivel2_gen/conteos#fasol_banco_regionales",
    as: :banco_regionales

  get "/fasol/banco_detalle/:regional" =>
  "sivel2_gen/conteos#fasol_banco_detalle",
    as: :banco_detalle

  get "/fasol/banco_detreg" =>
  "sivel2_gen/conteos#fasol_banco_detreg",
    as: :banco_detreg

  get "/orgsociales/jerarquia" => "msip/orgsociales#jerarquia",
    as: :jerarquia_orgsociales

  get '/personas/nombresrepetidos' => 'msip/personas#nombresrepetidos',
    as: :personas_nombresrepetidos

  namespace :admin do
    ab = Ability.new
    ab.tablasbasicas.each do |t|
      next unless t[0] == ""

      c = t[1].pluralize
      resources c.to_sym,
        path_names: { new: "nueva", edit: "edita" }
    end
  end

  root "sivel2_gen/hogar#index"
  # scope

  mount Jos19::Engine, at: "/", as: "jos19"
  mount Sivel2Gen::Engine, at: "/", as: "sivel2_gen"
  mount Cor1440Gen::Engine, at: "/", as: "cor1440_gen"
  mount Heb412Gen::Engine, at: "/", as: "heb412_gen"
  mount Mr519Gen::Engine, at: "/", as: "mr519_gen"
  mount Msip::Engine, at: "/", as: "msip"
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Casos" do %>
        <%= opcion_menu "Listado", sivel2_gen.casos_path,
          desplegable: true %>
        <% if can?(:new, Sivel2Gen::Caso) %>
          <%= opcion_menu "Nuevo Caso", sivel2_gen.new_caso_path,
            desplegable: true %>
          <!--%= opcion_menu "Refrescar Listado de Casos",
            sivel2_gen.casos_refresca_path,
            desplegable: true %-->
          <%= opcion_menu "Reporte de validación de casos", sivel2_gen.validarcasos_path,
            desplegable: true %>
          <%= opcion_menu "Reporte de casos repetidos", sivel2_gen.buscarrepetidos_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Conteo por demografía víctimas",
          sivel2_gen.conteos_personas_path,
          desplegable: true %>
        <%= opcion_menu "Listado de víctimas y casos",
          sivel2_gen.victimas_path,
          desplegable: true %>
        <%= opcion_menu "Conteo de victimizaciones individuales",
          sivel2_gen.conteos_victimizaciones_path,
          desplegable: true %>
        <%= opcion_menu "Conteo general de víctimizaciones",
          sivel2_gen.conteos_genvic_path,
          desplegable: true %>
        <%= opcion_menu "Graficar victimizaciones individuales",
          sivel2_gen.graficar_victimizaciones_individuales_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu "Tabla para web con totales",
          main_app.banco_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu "Tabla para web con totales por regional",
          main_app.banco_regionales_path,
          'data-turbo' => false,
          desplegable: true %>
        <%= opcion_menu "Acordeón para web con rango de edad y sexo",
          main_app.banco_detreg_path,
          'data-turbo' => false,
          desplegable: true %>

        <%= opcion_menu "Casos sobre OpenStreetMap",
          sivel2_gen.casos_mapaosm_path, desplegable: true %>
        <%= opcion_menu 'Mapa de victimizaciones individuales por departamento',
          sivel2_gen.mapadepvic_path,
          'data-turbo' => false,
          desplegable: true %>

      <% end %>
      <%= despliega_abajo "Entidades" do %>
        <%= opcion_menu "Listado",
          msip.orgsociales_path, desplegable: true %>
        <%= opcion_menu "Jeraraquía",
          main_app.jerarquia_orgsociales_path, desplegable: true %>
      <% end %>

      <%= despliega_abajo 'Proyectos y Actividades' do %>
        <%= opcion_menu 'Actividades', cor1440_gen.actividades_path,
          desplegable: true %>
        <%= opcion_menu 'Proyectos',
          cor1440_gen.proyectosfinancieros_path,
          desplegable: true %>
        <%= opcion_menu "Contar actividades por actividad de marco lógico",
          cor1440_gen.contar_actividades_path, desplegable: true %>
        <%= opcion_menu "Contar actividades por beneficiario y actividad de marco lógico",
          cor1440_gen.contar_actividades_beneficiarios_path,
          desplegable: true %>
        <%= opcion_menu 'Medición de indicadores',
          cor1440_gen.mindicadorespf_path, desplegable: true %>
      <% end %>
      <%= despliega_abajo 'Población vinculada' do %>
        <%= opcion_menu 'Listado',
          msip.personas_path, desplegable: true %>
        <%= opcion_menu 'Homonimos',
          main_app.homonimos_path, desplegable: true %>
        <%= opcion_menu 'Reporte de posibles nombres repetidos',
          main_app.personas_nombresrepetidos_path, desplegable: true %>
        <%= opcion_menu 'Reporte de aportantes',
          main_app.consaportantes_path, desplegable: true %>
        <%= opcion_menu 'Actualización masiva de aportes',
          main_app.aportes_actualizacion_masiva_path, desplegable: true %>
      <% end %>

    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Documentos" do %>
        <%= opcion_menu "Manual",
          'https://docs.google.com/document/d/1neMa3sBrrPDaW3_oWsK5ZjjWQ5BdXi2SmoM7AwvjJgo/edit?usp=sharing',
          target: '_blank', desplegable: true %>
        <%= opcion_menu "Nube", heb412_gen.sisini_path,
          desplegable: true %>
        <% if can? :manage, ::Heb412Gen::Plantillahcm %>
          <%= opcion_menu "Plantillas para listado",
            heb412_gen.plantillashcm_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Heb412Gen::Plantillahcr %>
          <%= opcion_menu "Plantillas para un registro",
            heb412_gen.plantillashcr_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y Tema del usuario", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
          <%= opcion_menu 'Ficha caso vertical ✓',
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical'
          %>
        <% else %>
          <%= opcion_menu 'Ficha caso vertical',
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% end %>
        <% if can? :read, Mr519Gen::Encuestausuario %>
          <%= opcion_menu 'Encuestas',
            mr519_gen.encuestasusuario_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Árbol de presuntos responsables",
          sivel2_gen.arbol_presponsables_path, desplegable: true %>
        <% if can? :manage, :tablasbasicas %>
          <%= opcion_menu "Tablas Básicas", sivel2_gen.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Respaldo7z %>
          <%= opcion_menu "Respaldo cifrado", msip.respaldo7z_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Msip::Bitacora %>
          <%= opcion_menu "Ver bitácoras",
            msip.bitacoras_path, desplegable: true %>
        <% end %>
        <%= opcion_menu "Espacio usado",
          msip.espacio_path, desplegable: true %>
        <%= opcion_menu "Ayuda sobre control de acceso",
          msip.ayuda_controldeacceso_path, desplegable: true %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}",
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", sivel2_gen.acercade_path %>
      <%= opcion_menu "Iniciar sesión", main_app.iniciar_sesion_path %>
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <span style='font-size: 0.8rem; text-align: left'>
    <%= Rails.configuration.x.sivel2_consweb_pie ?
      Rails.configuration.x.sivel2_consweb_pie.html_safe : '' %>
    <hr>
    <div align="right">
      Sistema de información de <a href="https://gitlab.com/pasosdeJesus/si_fasol">código abierto</a> desarrollado por <a href="https://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2024.

    </div>
  </span>
<% end %>

<%= render template: "layouts/msip/application" %>